# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")

    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
	 sign_apk(
	       alias: "key0",
	       keystore_path: "/Users/sushantkumar/Documents/Code/CloudKey/Flash1Key",
#       tsa: "http://timestamp.comodoca.com/rfc316",
#       signed_apk_path: options[:signed_apk_path],
     )
  end
  lane :release do
	gradle(
	  task: 'assemble',
	  build_type: 'Release'
	)
  end

end
